### PR TITLE
feature: Follow Symlinks when traversing scripts

### PR DESCRIPTION
**Pull request by impleri**
### Description

Adjust KubeJS.loadScripts to follow symlinks when traversing scripts.

### CODE REVIEW

**Comment by MaxNeedsSnacks** [comment]
Looks fine to me, I'm assuming the main use case for this would be to have cross-instance script folders for testing or something along those lines?

**Comment by squoshi** [comment]
> Looks fine to me, I'm assuming the main use case for this would be to have cross-instance script folders for testing or something along those lines?

Ideally dev servers or multiple instances. I tried making a server with it but it didn't work.

**Comment by MaxNeedsSnacks** [comment]
Hmm, can you give a little bit more detail about what the issue is here @squoshi? I'd like to see this merged with the other changes in the next release if possible

**Comment by impleri** [comment]
I linked a folder within `server_scripts`. I'm not sure if `kubejs` itself can be symlinked.

**Comment by MaxNeedsSnacks** [comment]
This PR shouldn't need to worry about that because it only addresses the script managers. So long as those work fine it's all good :P

**Comment by impleri** [comment]
It's also working for me if `server_scripits` is a symlink. So should work for anything at or under the script manager root directory.

**Comment by squoshi** [comment]
> Hmm, can you give a little bit more detail about what the issue is here @squoshi? I'd like to see this merged with the other changes in the next release if possible

KubeJS scripts didn't load. I don't know if it's a me problem or a KubeJS problem.
Checkmarks mean they work, X's mean they don't.
image

**Comment by MaxNeedsSnacks** [comment]
Again, symlinking the kubejs folder is not the concern here, we’re talking about the folders inside the kubejs folder for now

**Comment by MaxNeedsSnacks** [comment]
Looking for an update from @squoshi here, does the intended usecase (symlinking *subfolders* of ./kubejs/) work here?

**Comment by MaxNeedsSnacks** [comment]
Mostly waiting on a response from @squoshi, also, in theory it'd be more practical if the "kubejs" folder itself was also symlinkable, wouldn't it?

**Comment by impleri** [comment]
I just tested this and it indeed works for that effect.

ll-output

ll2-output

ll3-output

kube-log

Perhaps the issue is that a symlink is not the same as a Windows `.lnk` file?

**Comment by MaxNeedsSnacks** [comment]
Ah right, I was assuming they were using directory junctions (the NTFS version of directory symlinks)

**Comment by MaxNeedsSnacks** [comment]
Thanks for the contribution! We're currently still preparing for a new (possibly bigger) release of KubeJS so this change won't *immediately* be released, but it's now on the dev branch (and if applicable and I remember to do so, I'll be backporting it to 1.18 as well)

**Pull request merged**
