### PR TITLE
Loot Tables

### PR DESCRIPTION
**Pull request by lythowastaken**
Hello 👀

as loot tables currently just works for blocks with a few things I thought it would be cool to integrate a full loot table support with kubejs. 

API Example:
```js
onEvent("loot_tables", (event) => {
	// Example with modify();
	event.entities.modfy("minecraft:creeper", (table) => {
		// creates a new pool
		table.pool((pool) => {
			pool.setRolls(10);
			// pool.setUniformRolls(min, max);
			// pool.setBinomialRolls(n, p);

			pool.addEntry("minecraft:diamond"); // simple entry

			// use Ingredient.of or Item.of
			// count will auto insert loot table function for 'set_count'
			// nbt does the same for 'set_nbt'
			// adding chance will auto add the condition 'random_chance'
			// pool.addEntry(Ingredient.of("minecraft:diamond"));

			// tags works too!
			pool.addEntry(Ingredient.of("#forge:ores"));

			// addEntry can use an action too for further modifications
			pool.addEntry("minecraft:nether_star", entry => {
				// entry....
			});

			/*
				There are multiple pre defined conditions and functions as methods to help building loot tables.
				Ofc like in loot tables you can add conditions and functions to every part of the loot table where
				there are possible.
				Example: 	pool.entries[1].conditions....
							pool.entries[1].functions....
			*/
			pool.conditions.survivesExplosion();
			pool.matchTool("minecraft:wooden_pickaxe"); // or directly call it on the pool
			pool.killedByEntity("minecraft:zombie"); // helpful for the same behaviour like music disc drops from creeper
			pool.isOnFire(true); // helpful for the same behaviour like animals dropping cooked meat
			pool.killedByPlayer(); // example blazes only drop rods when killed by the player
			pool.biome("minecraft:jungle");
			// and more

			// functions
			pool.functions.setNbt({});
			pool.setCount(5); // or direct call without `.functions`
			pool.setUniformCount(0, 10);
			pool.setBinomialCount(2, 0.5);
			pool.furnaceSmelt();
			pool.limitCount(min, max);
			// and more
		});
	});
});
```

More:
- [X] Recreate the block loot table event behaviour with regex and co. 
  // not 100% like `block.loot_tables` because its one event for entites, chests, blocks etc.
- [X] More tests (I will upload a zip with a lot of tables which can be used as examples too)
- [x] Decide how to `inject` new tables. Technically we could just use `modfy()` and append new loot tables
- [x] Add a way to remove or clear tables (remove will probably result into null pointers for custom mods, need to test it)
- [ ] Write wiki article
- [x] Decide how to add chest loot for dungeons etc. What counts as dungeon? Some helper methods maybe
_**Dungeons handling is weird in mc. Its just easier to use `modify` or `merge` etc. later on the different chest names**_
- [x] Add functionality to call `pool.matchTool()` instead of `pool.conditions.matchTool()`

### CODE REVIEW

**Comment by MaxNeedsSnacks** [comment]
This is looking quite promising so far, let me know when it's ready for a review!

**Comment by lythowastaken** [comment]
Some tests
[test_loot_tables.zip](https://github.com/KubeJS-Mods/KubeJS/files/7145210/test_loot_tables.zip)

**Comment by lythowastaken** [comment]
## Here you will find stuff for the wiki article

**Comment by LatvianModder** [comment]
I didn't know this exists and made my own 😄 I will yoink some stuff from this later like the conditions etc

**Comment by lythowastaken** [comment]
> I didn't know this exists and made my own 😄 I will yoink some stuff from this later like the conditions etc

I saw you added the `addItem` with item support directly :p

Will rebase this PR today again to fix the conflicts

**Pull request closed without merging**
