### PR TITLE
(1.20.1) Make `allowAsyncStreams` affect initial recipe collection as well

### PR DESCRIPTION
**Pull request by 9thCore**
### Description 
`allowAsyncStreams`, despite its name, does not affect all asynchronous/parallel streams. It does affect `forEachRecipe` callbacks, but not the initial recipe load done by KubeJS, which can error mods such as Crossroads (#858) which [add to a list](https://github.com/Crossroads-Development/Crossroads/blob/1.19/src/main/java/com/Da_Technomancer/crossroads/api/alchemy/ReagentManager.java#L60) when a [recipe is initialised](https://github.com/Crossroads-Development/Crossroads/blob/1.20.1/src/main/java/com/Da_Technomancer/crossroads/crafting/ReagentRec.java#L70).
Behaviour is the same if `allowAsyncStreams` is `true`, which it is by default.

#### Example Script 
Prior to this change, the simple script below would ocassionally error Crossroads Reagent recipes (see issue linked above)
```js
ServerEvents.recipes(e => { e.remove("minecraft:diamond_pickaxe"); });
```
But now, if `allowAsyncStreams` is `false`, it doesn't! ...as far as I could tell, anyway.
by being a concurrency issue it's already a roll of the dice whether it's really "fixed" or i just rolled lucky many times; I've done about 20 consecutive reloads with no such warning and all recipes still existing, whereas it took 0 (initial world load) or 1 with it being `true` to trigger a concurrency error, so I have pretty high hopes in this solution ahaha

#### Other details 
I don't think it's likely to break anything, as all it does is change the streams for recipe load to not be parallel in case `allowAsyncStreams` is false. Addons should not be using this information nor interfacing with it in any way, I do believe.

### CODE REVIEW

**Comment by pietro-lopes** [comment]
At mean time, should be asked to Crossroads devs to make it safe.
We had exact same problem with Terrafirma and they did it safer. So we don't have take a performance hit just because a single mod.

**Comment by 9thCore** [comment]
would it not be better to have consistency? i'd assumed it would affect all asynchronous streams, given its name, until i looked into kjs' source to figure out what was going on
but i guess the performance concern makes sense (even if it's but in the rare case of mods malfunctioning because of this multithreading), i'll mention the case over there for the time being

**Comment by pietro-lopes** [comment]
Yes, I'm talking about *them* supporting concurrency. Should try to ask.

**Comment by 9thCore** [comment]
i got that part haha sorry if i wasnt clear, constructing a message right now since i need to find a concurrent alternative to `ArrayList` and im unsure how the only one i found, `CopyOnWriteArrayList`, really works

**Comment by 9thCore** [comment]
as shown by the pull request, issue has been solved on crossroads' end. sorry for the pr! wasn't aware tfc also had the same issue and how they fixed it

**Pull request closed without merging**
